theme: jekyll-theme-architect
title: yongjian's space
description: The evil deeds will eventually face retribution!
google_analytics: G-9KR0FRT5S5
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
